inherit_from:
  - .rubocop_airbnb.yml

LineLength:
  Max: 140

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'test/controllers/*'
    - 'vendor/**/*'
    - 'path/ruby'